# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x1c\x64\x65\x63\x65ntralized_data_syndicate\"\xc4\x01\n\x0c\x44\x61taNeedSpec\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x10\n\x08min_rows\x18\x03 \x01(\r\x12\x1e\n\x16max_null_rate_permille\x18\x04 \x01(\r\x12\x18\n\x10required_columns\x18\x05 \x03(\t\x12\x19\n\x11\x62udget_usdc_milli\x18\x06 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x04\"\x8d\x02\n\tDataOffer\x12\x10\n\x08offer_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x12\n\ndataset_id\x18\x03 \x01(\t\x12\x16\n\x0eseller_peer_id\x18\x04 \x01(\t\x12\x15\n\rseller_wallet\x18\x05 \x01(\t\x12\x18\n\x10price_usdc_milli\x18\x06 \x01(\r\x12\x10\n\x08zk_proof\x18\x07 \x01(\x0c\x12\x43\n\x0epublic_quality\x18\x08 \x01(\x0b\x32+.decentralized_data_syndicate.QualityReport\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x11\n\ttimestamp\x18\n \x01(\x04\"\x89\x01\n\rQualityReport\x12\x11\n\trow_count\x18\x01 \x01(\r\x12\x1a\n\x12null_rate_permille\x18\x02 \x01(\r\x12\x13\n\x0bschema_hash\x18\x03 \x01(\x0c\x12\x1e\n\x16\x65ntropy_score_permille\x18\x04 \x01(\r\x12\x14\n\x0cschema_match\x18\x05 \x01(\x08\"\xb8\x01\n\rApprovalEvent\x12\x10\n\x08offer_id\x18\x01 \x01(\t\x12\x12\n\ndataset_id\x18\x02 \x01(\t\x12\x14\n\x0c\x62uyer_wallet\x18\x03 \x01(\t\x12\x15\n\rseller_wallet\x18\x04 \x01(\t\x12\x18\n\x10price_usdc_milli\x18\x05 \x01(\x04\x12\x10\n\x08\x61pproved\x18\x06 \x01(\x08\x12\x11\n\ttimestamp\x18\x07 \x01(\x04\x12\x15\n\rapproval_hash\x18\x08 \x01(\x0c\"z\n\x0fPurchaseRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08offer_id\x18\x02 \x01(\t\x12\x14\n\x0c\x62uyer_wallet\x18\x03 \x01(\t\x12\x18\n\x10\x62uyer_public_key\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATANEEDSPEC']._serialized_start=49
  _globals['_DATANEEDSPEC']._serialized_end=245
  _globals['_DATAOFFER']._serialized_start=248
  _globals['_DATAOFFER']._serialized_end=517
  _globals['_QUALITYREPORT']._serialized_start=520
  _globals['_QUALITYREPORT']._serialized_end=657
  _globals['_APPROVALEVENT']._serialized_start=660
  _globals['_APPROVALEVENT']._serialized_end=844
  _globals['_PURCHASEREQUEST']._serialized_start=846
  _globals['_PURCHASEREQUEST']._serialized_end=968
# @@protoc_insertion_point(module_scope)
